name: traveler
services:
  globe:
    build:
      context: apps/globe
      target: development
    networks:
      - client-side
    volumes:
      - ./apps/globe/src:/code/src:ro

  elephant:
    build:
      context: apps/elephant
      target: development
    networks:
      - server-side
    volumes:
      - ./apps/elephant/src:/code/src
      - ./apps/elephant/configuration:/code/configuration
      - elephant-cache:/code/target
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  proxy:
    build:
      context: proxy
    restart: unless-stopped
    ports:
        - "80:80"
        - "443:443"
    networks:
      - client-side
      - server-side

networks:
  client-side: {}
  server-side: {}

volumes:
  elephant-cache: {}
  db-data: {}